export const SHOW_ERROR = 'SHOW_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'

export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_IN_ACTION = 'SIGN_IN_ACTION'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'

export const SET_TASKS_NAVIGATION = 'SET_TASKS_NAVIGATION'

export const FETCH_TASKS_ACTION = 'FETCH_TASKS_ACTION'
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE'

export const CREATE_TASK_ACTION = 'CREATE_TASK_ACTION'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE'

export const EDIT_TASK_ACTION = 'EDIT_TASK_ACTION'
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS'
export const EDIT_TASK_FAILURE = 'EDIT_TASK_FAILURE'

export const SET_CURRENT_TASK = 'SET_SURRENT_TASK'
export const SET_CURRENT_OPERATION = 'SET_CURRENT_OPERATION'
